version: '3.8'

services:
  est-mit-web:
    build:
      context: .
      target: development
    image: est-mit-invoice-importer-snyk
    command: extract-project-assets.sh
    entrypoint: /bin/sh
    volumes:
      - ./scripts/extract-project-assets.sh:/home/dotnet/extract-project-assets.sh
      - ./EST.MIT.InvoiceImporter/obj:/home/dotnet/snyk