version: '3.8'

services:
  est-mit-invoice-importer:
    build:
      target: development
    container_name: est-mit-invoice-importer
    entrypoint: dotnet watch --project ./EST.MIT.InvoiceImporter.Function.Test test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./test-output/'