version: '3.8'

services:
  est-mit-invoice-importer:
    build:
      target: development
    ports:
      - "3001:80"
    volumes:
      - ./EST.MIT.InvoiceImporter:/home/dotnet/EST.MIT.InvoiceImporter
      - ./EST.MIT.InvoiceImporter.Test:/home/dotnet/EST.MIT.InvoiceImporter.Test