version: '3.8'

services:
  est-mit-web:
    build:
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./EST.MIT.InvoiceImporter:/home/dotnet/EST.MIT.InvoiceImporter
      - ./EST.MIT.InvoiceImporter.Test:/home/dotnet/EST.MIT.InvoiceImporter.Test