version: '3.8'

services:
  est-mit-web:
    build:
      target: development
    container_name: est-mit-invoce-importer
    entrypoint: dotnet watch --project ./EST.MIT.InvoiceImporter.Test test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./test-output/'