version: '3.8'

services:
  est-mit-invoice-importer:
    build:
      context: .
      target: production
    image: est-mit-invoice-importer
    container_name: est-mit-invoice-importer
    environment:
      COMPlus_EnableDiagnostics: 0
