version: '3.8'

services:
  est-mit-invoice-importer:
    image: est-mit-invoice-importer-development
    container_name: est-mit-invoice-importer-development
    ports:
      - "3001:80"
    volumes:
      - ./ESTMITInvoiceImporterFunction:/home/dotnet/EST.MIT.InvoiceImporter.Function
      - ./ESTMITInvoiceImporterFunction.Test:/home/dotnet/EST.MIT.InvoiceImporter.Function.Test