version: '3.8'

services:
  est-mit-invoice-importer:
    build:
      target: development
    image: est-mit-invoice-importer
    container_name: est-mit-invoice-importer
    entrypoint: dotnet test ./EST.MIT.InvoiceImporter.Function.Test/EST.MIT.InvoiceImporter.Function.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./test-output/'
    volumes:
      - ./test-output:/home/dotnet/EST.MIT.InvoiceImporter.Function.Test/test-output
