{{- include "ffc-helm-library.container-config-map" (list . "est-mit-invoice-importer.config-map") -}}
{{- define "est-mit-invoice-importer.config-map" -}}
data:
  COMPlus_EnableDiagnostics: {{ .Values.container.comPlusEnableDiagnostics | quote }}
  PORT: {{ .Values.container.port | quote }}
{{- end -}}