{{- include "ffc-helm-library.container-config-map" (list . "est-mit-invoice-importer.config-map") -}}
{{- define "est-mit-invoice-importer.config-map" -}}
data:
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  FUNCTIONS_WORKER_RUNTIME: {{ quote .Values.container.functionsWorkerRuntime }}
  QueueConnectionString__queueServiceUri: {{ quote .Values.container.queueConnectionString__queueServiceUri }}
  QueueConnectionString__credential: {{ quote .Values.container.queueConnectionString__credential }}
  BlobConnectionString__blobServiceUri: {{ quote .Values.container.blobConnectionString__blobServiceUri }}
  BlobConnectionString__credential: {{ quote .Values.container.blobConnectionString__credential }}
  TableConnectionString__tableServiceUri: {{ quote .Values.container.tableConnectionString__tableServiceUri }}
  TableConnectionString__credential: {{ quote .Values.container.tableConnectionString__credential }}
  EventQueueName: {{ quote .Values.container.eventQueueName }}
  WebUIBaseUrl: {{ quote .Values.container.webUIBaseUrl }}
{{- end -}}
