{{- include "ffc-helm-library.container-secret" (list . "est-mit-invoice-importer.container-secret") -}}
{{- define "est-mit-invoice-importer.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  AzureWebJobsStorage: {{ quote .Values.container.azureWebJobsStorage }}
{{- end -}}
