{{- include "ffc-helm-library.deployment" (list . "est-mit-invoice-importer.deployment") -}}
{{- define "est-mit-invoice-importer.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "est-mit-invoice-importer.container") }}
{{- end -}}
